# Generated by Django 3.2 on 2021-04-22 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=False, upload_to='blogs/images/'),
            preserve_default=False,
        ),
    ]
